# This is a basic workflow to help you get started with Actions

name: Execute Change Actions of Main Branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    # paths: ["api/rest"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  detect-changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Runs a set of commands using the runners shell
      - name: Print Job Information
        run: |
          echo Running rest contract file generation change
          echo Trying to validate the change on the path api/rest

      - name: Get changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            rest:
              - api/rest/**
            async:
              - api/async/**
            database:
              - database/**

      #Read the Rest Api Contract Version from Metadata File
      - name: Read Rest Meta Properties
        id: read-rest-meta-properties
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.app.version' 'api/rest/metadata.yml'

      # Read the Async Api Contract from the Metadata File   
      - name: Read Async Meta Properties
        id: read-async-meta-properties
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.app.version' 'api/async/metadata.yml' 
      # Set's up JDK , Ant , Maven and other required Java Artifacts        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Check if the Rest Contract Files have been changed to prepare the artifacts
      - name: Execute Jar Actions on Rest Api Contract If Changed
        if: steps.changed-files-yaml.outputs.rest_any_changed == 'true'
        run: |
          echo "The Rest Contract Files Have changed"
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.rest_all_changed_files }}"
          cd api/rest
          mvn --batch-mode --update-snapshots deploy -Dapp.version=${{steps.read-rest-meta-properties.outputs.result}}
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
      # Check if the Async Contract Files have been changed to prepare the artifacts
      - name: Execute Jar Actions on Async Api Contract If Changed
        if: steps.changed-files-yaml.outputs.async_any_changed == 'true'
        run: |
          echo "The Async Contract Files Have changed "
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.async_all_changed_files }}"
          cd api/async
          mvn --batch-mode --update-snapshots deploy -Dapp.version=${{steps.read-async-meta-properties.outputs.result}}
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}