# This is a basic workflow to help you get started with Actions

name: Execute Change Actions of Main Branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types:
      - labeled
      # - edited
      # - unlabeled
      # - reopened
      - opened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  detect-changes:
    # Only run the job when these labels are detected on the issue
    if: ((contains(github.event.issue.labels.*.name, 'release-type-current') && contains(github.event.issue.labels.*.name, 'create-release'))) && (contains(github.event.issue.labels.*.name, 'major') || contains(github.event.issue.labels.*.name, 'minor'))
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      discussions: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Default Value for Release Type
        run: |
          echo "RELEASE_TYPE=minor" >> "$GITHUB_ENV"

      - name: Determine the release type is Major
        if: contains(github.event.issue.labels.*.name, 'major')
        run: |
          echo "RELEASE_TYPE=major" >> "$GITHUB_ENV"
      - name: Determine the release type is Minor
        if: contains(github.event.issue.labels.*.name, 'minor')
        run: |
          echo "RELEASE_TYPE=minor" >> "$GITHUB_ENV"
      - name: Add Comments to the ticket for Release Preparation
        run: |
          echo gh --version
          gh issue comment ${{github.event.issue.number}} -b ":rocket: Hola! Welcome To The Release Preparation. Just sit back and relax while we prepare the release for you. We will Notify you here once the Release Process is complete."
          gh issue comment ${{github.event.issue.number}} -b "Triggering Release Process with Type: ${RELEASE_TYPE}"
        env:
          GH_TOKEN: ${{secrets.ACCESS_TOKEN}}

      # Refer here for documentation on this runner: https://github.com/zendesk/action-create-release/tree/master#example-workflow---create-a-release
      - name: Create Release With Tag
        id: create-release
        uses: zendesk/action-create-release@v1
        with:
          auto_increment_type: $RELEASE_TYPE
          prerelease: false
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
      
      - name: Generate Release Notes
        run: echo ${{github.sha}} > Release.txt

      - name: Upload Release Artifacts
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{steps.create-release.outputs.upload_url}}
          asset_content_type: application/text
          asset_name: Release.txt
          asset_path: Release.txt
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}

      - name: Comment and Close the Release Issue
        run: |
          gh issue comment ${{github.event.issue.number}} -b ":rocket: The release process is successfully completed. No Action Required from user end. This ticket will be auto-closed. Please Re-Open the ticket In Case any Further Release is required."
          gh issue close ${{github.event.issue.number}} -r "Completed"
        env:
          GH_TOKEN: ${{secrets.ACCESS_TOKEN}}
