# This is a basic workflow to help you get started with Actions

name: Execute Change Actions of Main Branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues: 
    types:  [ opened, labeled, reopened, closed ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  detect-changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      discussions: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Execute Gh Commands
        run: |
            gh --version
            gh issue list --label bug
        env:
          GH_TOKEN: ${{secrets.ACCESS_TOKEN}}

      - name: Create Release 
        if: contains(github.event.issue.labels.*.name, 'release-type-current') 
        run: |
            echo "creating release v0.0.1 for issue ${{github.event.issue.id}}"
            echo "Contains release type current"
        env:
          GH_TOKEN: ${{secrets.ACCESS_TOKEN}}