# This is a basic workflow to help you get started with Actions

name: Execute Upload Artifacts on Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  detect-changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #Read the Rest Api Contract Version from Metadata File
      - name: Read Rest Meta Properties
        id: read-rest-meta-properties
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.app.version' 'api/rest/metadata.yml'

      # Read the Async Api Contract from the Metadata File
      - name: Read Async Meta Properties
        id: read-async-meta-properties
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.app.version' 'api/async/metadata.yml'
      # Set's up JDK , Ant , Maven and other required Java Artifacts
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Check if the Rest Contract Files have been changed to prepare the artifacts
      - name: Execute Jar Actions on Rest Api Contract
        run: |
          cd api/rest
          mvn package -Dapp.version=${{steps.read-rest-meta-properties.outputs.result}}
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
      # Check if the Async Contract Files have been changed to prepare the artifacts
      - name: Execute Jar Actions on Async Api Contract
        run: |
          cd api/async
          mvn package -Dapp.version=${{steps.read-async-meta-properties.outputs.result}}
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
      - name: Upload Artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          append_body: true
          files: |
            **/*.jar
